In [89]:
import numpy as np

X = np.array([[1.0,0.,2.],
              [1.,2.,0.],
              [1.,2,2.],
              [1.,1.,1.]])

y = np.array([[1],[-1],[1],[-1]])
beta = np.array([0.,0.,0.])
N=X.shape[0]

def test_condition(X, beta, y):
    
    cond = np.multiply(X@beta,y.T)   
    return cond<1

def primal_grad (X, beta, y, lamb=1):
    
    cond = test_condition(X, beta, y)[0]
    X = X[cond,]
    y = y[cond,]
    print(cond)
    if(sum(cond)==0):
        grad = lamb*beta
    else:
        grad = np.mean(-np.multiply(y, X), axis=0) + lamb*beta
    print("Grad:" , grad)
    return grad

In [90]:
n_iter = 4
lamb = 1
lr = 1
n_minibatch = 2 
t=0
for i in range(n_iter):
    
    for j in range(0,n_minibatch):
        t+=1
        lr = 1/(lamb*t)
        X_ = X[((j)*n_minibatch):((j+1)*n_minibatch),]
        y_ = y[((j)*n_minibatch):((j+1)*n_minibatch),]
        print(X_)
        grad = primal_grad(X_, beta, y_, lamb)
        beta_tilde = beta - lr*grad
        magn_beta = np.linalg.norm(beta_tilde)
        norm = max(1, np.sqrt(lamb)*magn_beta)
        beta = beta_tilde/norm
        print("Norm:", norm)
        print("Beta:", beta)


[[1. 0. 2.]
 [1. 2. 0.]]
[ True  True]
Grad: [ 0.  1. -1.]
Norm: 1.4142135623730951
Beta: [ 0.         -0.70710678  0.70710678]
[[1. 2. 2.]
 [1. 1. 1.]]
[ True  True]
Grad: [ 0.         -1.20710678  0.20710678]
Norm: 1
Beta: [ 0.         -0.10355339  0.60355339]
[[1. 0. 2.]
 [1. 2. 0.]]
[False  True]
Grad: [1.         1.89644661 0.60355339]
Norm: 1
Beta: [-0.33333333 -0.73570226  0.40236893]
[[1. 2. 2.]
 [1. 1. 1.]]
[ True  True]
Grad: [-0.33333333 -1.23570226 -0.09763107]
Norm: 1
Beta: [-0.25      -0.4267767  0.4267767]
[[1. 0. 2.]
 [1. 2. 0.]]
[ True False]
Grad: [-1.25      -0.4267767 -1.5732233]
Norm: 1
Beta: [ 0.         -0.34142136  0.74142136]
[[1. 2. 2.]
 [1. 1. 1.]]
[ True  True]
Grad: [ 0.         -0.84142136  0.24142136]
Norm: 1
Beta: [ 0.         -0.20118446  0.70118446]
[[1. 0. 2.]
 [1. 2. 0.]]
[False  True]
Grad: [1.         1.79881554 0.70118446]
Norm: 1
Beta: [-0.14285714 -0.45815811  0.60101525]
[[1. 2. 2.]
 [1. 1. 1.]]
[ True  True]
Grad: [-0.14285714 -0.95815811  0.1